[tool.poetry]
name = "nonebot-adapter-cqhttp"
version = "2.0.0-beta.1"
description = "OneBot(CQHTTP) adapter for nonebot2"
authors = ["yanyongyu <yyy@nonebot.dev>"]
license = "MIT"
readme = "README.md"
homepage = "https://onebot.adapters.nonebot.dev/"
repository = "https://github.com/nonebot/adapter-onebot"
documentation = "https://onebot.adapters.nonebot.dev/"
keywords = ["bot", "qq", "qqbot", "coolq", "cqhttp"]
classifiers = [
  "Development Status :: 7 - Inactive",
  "Framework :: Robot Framework",
  "Framework :: Robot Framework :: Library",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]
packages = [
  { include = "nonebot" }
]

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot-adapter-onebot = "*"

[tool.poetry.dev-dependencies]

# [[tool.poetry.source]]
# name = "aliyun"
# url = "https://mirrors.aliyun.com/pypi/simple/"
# default = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
